name: Simple Flask CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Flask app syntax
        run: python -m py_compile app.py

      - name: Import Flask app
        run: python -c "import app; print('Flask app imported successfully!')"
